DROP DATABASE IF EXISTS APNIDUKAAN;
CREATE DATABASE APNIDUKAAN;
USE APNIDUKAAN;

CREATE TABLE PRODUCT(
	PRODUCT_ID INT AUTO_INCREMENT,
	NAME VARCHAR(500) NOT NULL,
	DESCRIPTION VARCHAR(1000) NOT NULL,
	CATEGORY VARCHAR(200) NOT NULL,
	BRAND VARCHAR(250) NOT NULL,
	PRICE BIGINT NOT NULL,
	QUANTITY SMALLINT NOT NULL,
	CONSTRAINT PRODUCT_ID_PK PRIMARY KEY ( PRODUCT_ID )
);

CREATE TABLE CUSTOMER(
	EMAIL_ID VARCHAR(50),
	NAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(70) NOT NULL,
	PHONE_NUMBER VARCHAR(10) NOT NULL UNIQUE,
	ADDRESS VARCHAR(500),
	CONSTRAINT CUSTOMER_EMAIL_ID_PK PRIMARY KEY (EMAIL_ID)
);

CREATE TABLE CUSTOMER_CART(
	CART_ID INT auto_increment,
    CUSTOMER_EMAIL_ID VARCHAR(50),
	constraint CUSTOMER_CART_ID_PK primary key (CART_ID)
);

CREATE TABLE CART_PRODUCT(
	CART_PRODUCT_ID int AUTO_INCREMENT,
	CART_ID INT,
	PRODUCT_ID INT NOT NULL,
	QUANTITY SMALLINT,
	CONSTRAINT CART_PRODUCT_ID_PK PRIMARY KEY ( CART_PRODUCT_ID ),
	CONSTRAINT CART_PRODUCT_ID_CUSTOMER_CART_FK FOREIGN KEY (CART_ID) REFERENCES CUSTOMER_CART (CART_ID) 
);

CREATE TABLE ORDERS (
	ORDER_ID BIGINT NOT NULL auto_increment,
	DATE_OF_ORDER DATETIME NOT NULL,
	TOTAL_PRICE DECIMAL(12,2) NOT NULL,
	ORDER_STATUS VARCHAR(20) NOT NULL,
	PAYMENT_THROUGH VARCHAR(20) NOT NULL, 
	DATE_OF_DELIVERY DATETIME,
     CUSTOMER_EMAIL_ID VARCHAR(50),
	DISCOUNT DECIMAL(5,2) ,
	DELIVERY_ADDRESS VARCHAR(500),
	constraint ORDER_ID_PK primary key (ORDER_ID)
);
CREATE TABLE ORDERED_PRODUCT (
    ORDERED_PRODUCT_ID INT auto_increment,
	ORDER_ID BIGINT ,
	PRODUCT_ID INT,
	QUANTITY INT,
	constraint ORDERED_PRODUCT_ID_PK primary key ( ORDERED_PRODUCT_ID),
	constraint ORDERED_PRODUCT_ID_ORDER_FK foreign key (ORDER_ID)
    references ORDERS(ORDER_ID)
);

CREATE TABLE CARD( 
	CARD_ID INT auto_increment,
	CARD_TYPE VARCHAR(11) NOT NULL,
	CARD_NUMBER VARCHAR(16) NOT NULL,
	CVV VARCHAR(70) NOT NULL,
	EXPIRY_DATE DATETIME NOT NULL,
	NAME_ON_CARD VARCHAR(50) NOT NULL,
    CUSTOMER_EMAIL_ID VARCHAR(50),
	constraint CARD_ID_PK primary key ( CARD_ID )
);

CREATE TABLE TRANSACTION
(
	TRANSACTION_ID INT auto_increment,
	ORDER_ID INT  NOT NULL,
	CARD_ID INT NOT NULL,
	TOTAL_PRICE DECIMAL(12,2) NOT NULL,
	TRANSACTION_STATUS VARCHAR(50),
	TRANSACTION_DATE DATETIME NOT NULL,
	constraint TRANSACTION_ID_PK primary key ( TRANSACTION_ID )
);

