DROP DATABASE IF EXISTS APNIDUKAAN;
CREATE DATABASE APNIDUKAAN;
USE APNIDUKAAN;

CREATE TABLE PRODUCT(
	PRODUCT_ID INT AUTO_INCREMENT,
	NAME VARCHAR(500) NOT NULL,
	DESCRIPTION VARCHAR(1000) NOT NULL,
	CATEGORY VARCHAR(200) NOT NULL,
	BRAND VARCHAR(250) NOT NULL,
	PRICE BIGINT NOT NULL,
	QUANTITY SMALLINT NOT NULL,
	CONSTRAINT PRODUCT_ID_PK PRIMARY KEY ( PRODUCT_ID )
);

CREATE TABLE CUSTOMER(
	EMAIL_ID VARCHAR(50),
	NAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(70) NOT NULL,
	PHONE_NUMBER VARCHAR(10) NOT NULL UNIQUE,
	ADDRESS VARCHAR(500),
	CONSTRAINT CUSTOMER_EMAIL_ID_PK PRIMARY KEY (EMAIL_ID)
);
